# Generated by Django 4.1 on 2022-11-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese sus nombres', max_length=200)),
                ('apellido', models.CharField(help_text='Ingrese sus apellidos', max_length=200)),
                ('fecha_nac', models.DateField(blank=True, help_text='Ingrese su fecha de nacimiento', null=True)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(blank=True, help_text='Indique un correo válido', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del producto', max_length=200)),
                ('stock', models.IntegerField(help_text='Ingrese cantidad en stock')),
            ],
        ),
    ]
